#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

# remove the default Nf=ginx configuration
rm /etc/nginx/sites-enabled/default
#configure nginx to listen to port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
sudo service nginx restart
