#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx start
# terminates the first nginx process
kill "$(pgrep 'nginx' | head -1)"  
